title: Dave Cross
locale: en_GB
description: Web Development and CI/CD Engineer · Author / Publisher · Digital Mentor
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-seo-tag

logo: img/dc-cartoon-sq.png
og_image: /img/dc-cartoon.png

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-4E7LRJH94L"

atom_feed:
  hide: true

footer:
  links:
    - label: "Feed"
      url: "https://davorg.theplanetarium.org/atom.xml"
      icon: "fa-solid fa-rss"
    - label: "Contact"
      url: "/contact/"
      icon: "fa-solid fa-pen"
    - label: "Links"
      url: "https://links.davecross.co.uk/"
      icon: "fa-solid fa-link"

defaults:
  - scope:
      path: ""
    values:
      layout: single
      image: /img/dc-cartoon-sq.png

include:
  - assets/css/custom.css
